# TouchDesigner <- DSI-Streamer TCP 연결 셋업 스크립트
# =============================================================================
# 이 스크립트를 "TouchDesigner 안에서" 한 번 실행하면, DSI-Streamer 앱의 TCP/IP
# 스트림(기본 127.0.0.1:8844)에 붙는 TCP/IP DAT 를 만들고 바로 연결합니다.
# DSI-Streamer 의 TCP/IP 상태가 그 순간 'connected' 로 바뀝니다.
#
# 실행 방법 (둘 중 하나):
#   A) 텍스트포트에서:  Alt+T 로 Textport 를 열고, 이 파일 내용을 통째로 붙여넣고 Enter.
#   B) Text DAT 로:     Text DAT 를 만들어 이 내용을 붙여넣고, 노드 우클릭 -> Run Script.
#
# 실행하면 두 노드가 생깁니다:
#   - dsi_streamer            (TCP/IP DAT, DSI-Streamer 서버에 클라이언트로 접속)
#   - dsi_streamer_callbacks  (연결/수신/종료 콜백 Text DAT)
#
# 사전 조건: DSI-Streamer 앱에서 헤드셋이 연결되어 있고, 'TCP/IP' 스트리밍이 Start 되어
# 서버가 열려 있어야 합니다. (확인:  python dsi_connect.py tcp)
# =============================================================================

# --- 설정 --------------------------------------------------------------------
HOST = '127.0.0.1'       # DSI-Streamer 가 열려 있는 IP (다른 PC면 그 IP)
PORT = 8844              # DSI-Streamer TCP/IP 스트리밍 포트 (앱 설정과 일치)
PARENT = ''              # 노드를 만들 위치. ''(빈값)이면 메인 컨테이너를 자동 탐지.
                         # 특정 위치에 넣고 싶으면 경로 지정 (예: '/project1').
NAME = 'dsi_streamer'
CALLBACKS_NAME = 'dsi_streamer_callbacks'

# TCP/IP DAT 콜백. 연결/수신/종료를 Textport 에 찍고, 수신량을 DAT storage 에 누적합니다.
CALLBACKS_SRC = r'''# dsi_streamer_callbacks - auto-generated by td_dsi_setup.py
# Callbacks for the TCP/IP DAT connected to the DSI-Streamer TCP server.

def _bump(dat, key, n=1):
    try:
        dat.store(key, (dat.fetch(key, 0) or 0) + n)
    except Exception:
        pass

def _where(dat):
    try:
        return '%s:%s' % (dat.par.netaddress.eval(), dat.par.port.eval())
    except Exception:
        return dat.path

def onConnect(dat):
    dat.store('connected', True)
    dat.store('bytes', 0)
    dat.store('rows', 0)
    print('[DSI] connected ->', _where(dat))
    return

def onDisconnect(dat):
    dat.store('connected', False)
    print('[DSI] disconnected <-', _where(dat))
    return

# TD passes onReceive(dat, rowIndex, message, bytes, peer); defaults + *args keep
# this tolerant across TouchDesigner versions.
def onReceive(dat, rowIndex=None, message=None, bytes=None, peer=None, *args):
    _bump(dat, 'rows', 1)
    try:
        n = len(bytes) if bytes is not None else (len(message) if message else 0)
    except Exception:
        n = 0
    _bump(dat, 'bytes', n)
    return
'''


def _setpar(o, names, value):
    """Set the first matching parameter (case-insensitive); return its name or None.

    TCP/IP DAT parameter names vary slightly across TD versions, so we try
    several candidates and ignore the ones that don't exist / don't take value.
    """
    low = {p.name.lower(): p for p in o.pars()}
    for n in names:
        p = low.get(n)
        if p is not None:
            try:
                p.val = value
                return n
            except Exception:
                pass
    return None


def _pick_parent():
    """Where to place the nodes. Explicit PARENT wins; else auto-detect the main
    container (the busiest COMP under root), else fall back to root."""
    if PARENT:
        p = op(PARENT)  # noqa: F821
        if p is not None:
            return p
    root = op('/')  # noqa: F821
    if root is None:
        return None
    try:
        comps = [c for c in root.children if getattr(c, 'isCOMP', False)]
        comps = [c for c in comps if not c.name.startswith(('local', 'sys'))]
        if comps:
            comps.sort(key=lambda c: len(c.findChildren(maxDepth=99)), reverse=True)
            return comps[0]
    except Exception:
        pass
    return root


def setup():
    parent_op = _pick_parent()
    if parent_op is None:
        raise RuntimeError('parent not found (op("/") returned None)')

    cb = parent_op.op(CALLBACKS_NAME)
    if cb is None:
        cb = parent_op.create(textDAT, CALLBACKS_NAME)  # noqa: F821
    cb.text = CALLBACKS_SRC

    dat = parent_op.op(NAME)
    if dat is None:
        dat = parent_op.create(tcpipDAT, NAME)  # noqa: F821

    try:
        cb.nodeX, cb.nodeY = 0, -200
        dat.nodeX, dat.nodeY = 0, 0
    except Exception:
        pass

    # off -> configure -> on, so a stale socket reconnects cleanly.
    _setpar(dat, ['active'], False)
    got_addr = _setpar(dat, ['netaddress', 'address', 'netaddr', 'ip', 'host'], HOST)
    got_port = _setpar(dat, ['port', 'netport'], PORT)
    got_cb = _setpar(dat, ['callbacks', 'callbacksdat', 'callbackdat'], cb.path)
    _setpar(dat, ['active'], True)

    print('=' * 60)
    print('DSI-Streamer -> TouchDesigner 연결 설정 완료')
    print('  container :', parent_op.path, '(자동 탐지)' if not PARENT else '')
    print('  node      :', dat.path)
    print('  callbacks :', cb.path, '' if got_cb else '(콜백 파라미터 못 찾음!)')
    print('  target    : %s:%s' % (HOST, PORT),
          '' if (got_addr and got_port) else '(주소/포트 파라미터 일부 못 찾음)')
    print('  active    : True')
    if not got_addr or not got_port:
        print('  ! 이 TD 버전의 TCP/IP DAT 파라미터명이 달라 일부를 자동 설정 못했습니다.')
        print('    노드를 열어 Network Address/Port 를 %s / %s 로 직접 확인하세요.' % (HOST, PORT))
    print('-' * 60)
    print('DSI-Streamer 앱의 TCP/IP 상태가 이제 connected(초록) 로 바뀌었는지 확인하세요.')
    print("연결/수신 확인:  op('%s').fetch('connected', False),"
          " op('%s').fetch('bytes', 0)" % (dat.path, dat.path))
    print('※ 이 노드를 파일에 남기려면 지금 프로젝트를 저장하세요 (Ctrl+S).')

    # 약 1초 뒤 실제 연결/수신 상태를 Textport 에 한 번 더 찍어 줍니다.
    try:
        run("print('[DSI] 1s 후 상태: connected=', op(%r).fetch('connected', False),"
            " ' bytes=', op(%r).fetch('bytes', 0))" % (dat.path, dat.path),
            delayFrames=60)  # noqa: F821  (run is a TD global)
    except Exception:
        pass
    print('=' * 60)
    return dat


# `op` only exists inside TouchDesigner. When this file is merely imported
# (tests / terminal), nothing runs.
try:
    op  # noqa: F821, B018
    _IN_TD = True
except NameError:
    _IN_TD = False

if _IN_TD:
    setup()
