# TouchDesigner Bridge - setup script
# =============================================================================
# 이 스크립트를 "TouchDesigner 안에서" 한 번 실행하면, 터미널의 toe_ctl.py 가
# 붙을 수 있는 작은 HTTP 서버(WebServer DAT)를 자동으로 만들어 줍니다.
#
# 실행 방법 (둘 중 하나):
#   A) 텍스트포트에서:  Alt+T 로 Textport 를 열고, 이 파일 내용을 통째로 붙여넣고 Enter.
#   B) Text DAT 로:     Text DAT 를 만들어 이 내용을 붙여넣고, 노드 우클릭 -> Run Script.
#
# 실행하면 root('/') 아래에 두 노드가 생깁니다:
#   - td_bridge_server      (Web Server DAT, 포트 9980 에서 대기)
#   - td_bridge_callbacks   (콜백 코드가 담긴 Text DAT)
# =============================================================================

# --- 설정 --------------------------------------------------------------------
PORT = 9980              # 터미널 클라이언트가 접속할 포트
PARENT = '/'             # 브릿지를 만들 위치 (보통 루트)
SERVER_NAME = 'td_bridge_server'
CALLBACKS_NAME = 'td_bridge_callbacks'

# WebServer DAT 콜백 코드 (여기가 실제로 명령을 받아 실행하는 부분).
# TOKEN 을 비워두면 인증 없이 로컬에서 바로 씁니다. 공유 네트워크라면 값을 채우고
# toe_ctl.py 쪽에도 같은 토큰을 주세요.
CALLBACKS_SRC = r'''# td_bridge_callbacks - auto-generated by td_setup.py
# WebServer DAT callbacks: receives POST /exec {"code": "...", "token": "..."},
# runs the code inside TouchDesigner, returns {"ok","stdout","value","error"}.
import json
import io
import contextlib
import traceback

TOKEN = ''  # keep in sync with td_setup.py; '' disables auth

_NS = {}

def _seed_ns():
    if _NS.get('_seeded'):
        return
    _NS['__builtins__'] = __builtins__
    for _name in ('op', 'ops', 'root', 'me', 'parent', 'var', 'mod', 'iop',
                  'ipar', 'tdu', 'TDF', 'project', 'ui', 'absTime', 'run'):
        try:
            _NS[_name] = eval(_name)
        except Exception:
            pass
    _NS['_seeded'] = True

def _run_code(code):
    _seed_ns()
    out = {'ok': True, 'stdout': '', 'value': None, 'error': None}
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            try:
                compiled = compile(code, '<bridge>', 'eval')
                _v = eval(compiled, _NS)
                out['value'] = None if _v is None else repr(_v)
            except SyntaxError:
                exec(compile(code, '<bridge>', 'exec'), _NS)
    except Exception:
        out['ok'] = False
        out['error'] = traceback.format_exc()
    out['stdout'] = buf.getvalue()
    return out

def _json(response, status, obj):
    response['statusCode'] = status
    response['statusReason'] = 'OK' if status == 200 else 'Error'
    response['content-type'] = 'application/json'
    response['data'] = json.dumps(obj)
    return response

def onHTTPRequest(webServerDAT, request, response):
    uri = (request.get('uri') or '/').rstrip('/') or '/'
    if uri in ('/', '/ping'):
        return _json(response, 200, {'ok': True, 'pong': True})
    if uri == '/exec':
        raw = request.get('data') or ''
        if isinstance(raw, bytes):
            raw = raw.decode('utf-8', 'replace')
        code, token = '', ''
        try:
            payload = json.loads(raw) if raw else {}
            code = payload.get('code', '')
            token = payload.get('token', '')
        except Exception:
            code = raw
        if TOKEN and token != TOKEN:
            return _json(response, 200, {'ok': False, 'stdout': '', 'value': None,
                                         'error': 'bad token'})
        return _json(response, 200, _run_code(code))
    return _json(response, 200, {'ok': False, 'stdout': '', 'value': None,
                                 'error': 'unknown path: ' + uri})

def onWebSocketOpen(webServerDAT, client, uri):
    return

def onWebSocketClose(webServerDAT, client):
    return

def onWebSocketReceiveText(webServerDAT, client, data):
    return

def onWebSocketReceiveBinary(webServerDAT, client, data):
    return

def onServerStart(webServerDAT):
    return

def onServerStop(webServerDAT):
    return
'''


def setup():
    parent_op = op(PARENT)  # noqa: F821  (op is a TouchDesigner global)
    if parent_op is None:
        raise RuntimeError('parent not found: ' + PARENT)

    cb = parent_op.op(CALLBACKS_NAME)
    if cb is None:
        cb = parent_op.create(textDAT, CALLBACKS_NAME)  # noqa: F821
    cb.text = CALLBACKS_SRC

    ws = parent_op.op(SERVER_NAME)
    if ws is None:
        ws = parent_op.create(webserverDAT, SERVER_NAME)  # noqa: F821

    # lay the two nodes out next to each other so they are easy to find
    try:
        cb.nodeX, cb.nodeY = 0, -200
        ws.nodeX, ws.nodeY = 0, 0
    except Exception:
        pass

    ws.par.active = False
    ws.par.port = PORT
    ws.par.callbacks = cb.path
    ws.par.active = True

    print('=' * 60)
    print('TD bridge ready.')
    print('  server    :', ws.path)
    print('  callbacks :', cb.path)
    print('  port      :', PORT)
    print('  auth      :', 'token required' if "TOKEN = ''" not in CALLBACKS_SRC else 'none (localhost)')
    print('From a terminal:  python toe_ctl.py --port %d' % PORT)
    print('=' * 60)
    return ws


# `op` only exists inside TouchDesigner. When this file is merely imported by
# the test suite or the terminal client, nothing runs.
try:
    op  # noqa: F821, B018
    _IN_TD = True
except NameError:
    _IN_TD = False

if _IN_TD:
    setup()
